stages:
  - build

image: registry.klsmartin-development.de:443/platform/meta-kls/toolchain:2.4.7

release:
  tags: [ docker ]
  stage: build
  variables:
    BUILDTYPE: 'release'
    MESON_FLAGS: '-Dstrip=true -Dlvgl:color_depth=16'
  script:
    - meson --buildtype=${BUILDTYPE} ${MESON_FLAGS} build
    - env DESTDIR=sysroot ninja -C build install
  artifacts:
    paths:
      - build/sysroot/

release-fb:
  extends: release
  variables:
    MESON_FLAGS: '-Dstrip=true -Dlvgl:color_depth=16 -Dlv_drivers:display_backend=fb'