stages:
  - build

image: registry.klsmartin-development.de:443/platform/meta-kls:2.3.1

release:
  tags: [ docker ]
  stage: build
  variables:
    BUILDTYPE: 'release'
    CROSSFILE: 'meta-kls_2.3.1.cross'
  before_script:
    # use the most recent meson version.
    - pip install git+https://github.com/mesonbuild/meson.git ninja
  script:
    - meson --cross-file=${CROSSFILE} --buildtype=${BUILDTYPE} -Dstrip=true build
    - env DESTDIR=sysroot ninja -C build install
  artifacts:
    paths:
      - sysroot/
